repos:
    - repo: local
      hooks:
          - id: no-spicy-exif
            name: Ban spicy exif data
            description: Ensures that there is no sensitive exif data committed
            language: system
            entry: exiftool -gps:all= -overwrite_original
            exclude_types: ["svg"]
            types: ["image"]
